import {
  Activity,
  AlertTriangle,
  Database,
  FileCode,
  FlaskConical,
  GitBranch,
  Globe,
  Key,
  LayoutDashboard,
  Link,
  Monitor,
  Network,
  RefreshCw,
  Search,
  Server,
  Settings,
  Shield,
  ShieldAlert,
  Sparkles,
  Terminal,
  Wrench,
} from 'lucide-react';
import type {AiDenoiseModuleId, JsonValue, ModuleAction, ModuleConfig, TaskReportExportFormat} from '../domain/types';

export const TASK_REPORT_EXPORT_OPTIONS: Array<{ label: string; value: TaskReportExportFormat }> = [
  { label: '表格格式', value: 'excel' },
  { label: 'HTML格式', value: 'html' },
  { label: 'AI报告（Markdown）', value: 'ai_markdown' },
];

export const TASK_REPORT_EXPORT_LABELS: Record<TaskReportExportFormat, string> = {
  excel: '表格',
  html: 'HTML',
  ai_markdown: 'AI报告（Markdown）',
};

export const HYPERLINK_MODULE_COLUMN_MAP: Record<string, string[]> = {
  site: ['site'],
  url: ['url'],
  fileleak: ['url'],
  vuln: ['target'],
  nuclei_result: ['vuln_url'],
  wih: ['content', 'source', 'site'],
  wih_endpoint: ['target', 'page_url', 'url'],
};

export const AI_ANALYSIS_SEARCH_OPTIONS: Array<{ label: string; value: string }> = [
  { label: '全部', value: '' },
  { label: '未分析', value: 'unanalyzed' },
  { label: '安全/正常', value: 'safe' },
  { label: '可疑', value: 'suspicious' },
  { label: '危险', value: 'danger' },
  { label: '可信', value: 'trusted' },
  { label: '疑似误报', value: 'suspected_fp' },
];

export const AI_WIH_ENDPOINT_ANALYSIS_SEARCH_OPTIONS: Array<{ label: string; value: string }> = [
  { label: '全部', value: '' },
  { label: '未分析', value: 'unanalyzed' },
  { label: '高价值', value: 'high_value' },
  { label: '中价值', value: 'medium_value' },
  { label: '无价值', value: 'no_value' },
];

// 状态实时性要求高的模块（运行中/排队中语义）：列表缓存 staleTime 恒为 0，
// 其余模块 30s 内复用缓存（docs/04 数据层规则：运行中短、已完结长）。
export const LIVE_STATUS_MODULE_IDS = new Set([
  'task',
  'task_schedule',
  'scheduler',
  'github_task',
  'github_scheduler',
]);

export const AI_DENOISE_MODULE_IDS = ['site', 'fileleak', 'cert', 'url', 'wih_endpoint', 'vuln', 'nuclei_result'] as const;

export const AI_DENOISE_MODULE_LABEL_MAP: Record<AiDenoiseModuleId, string> = {
  site: '站点',
  fileleak: '目录扫描',
  cert: 'SSL证书',
  url: 'URL信息',
  wih_endpoint: 'WIH接口',
  vuln: '风险',
  nuclei_result: 'PoC风险',
};

export function canToggleHyperlink(moduleId: string): boolean {
  return Array.isArray(HYPERLINK_MODULE_COLUMN_MAP[moduleId]);
}

export function isHyperlinkEnabledColumn(moduleId: string, column: string): boolean {
  const columns = HYPERLINK_MODULE_COLUMN_MAP[moduleId];
  return Array.isArray(columns) && columns.includes(column);
}

export function isAiDenoiseModule(moduleId: string): moduleId is AiDenoiseModuleId {
  return (AI_DENOISE_MODULE_IDS as readonly string[]).includes(moduleId);
}

export const modules: ModuleConfig[] = [
  {
    id: 'dashboard',
    label: '我的仪表盘',
    description: '实时总览任务、资产、风险与系统状态',
    group: '核心功能',
    icon: LayoutDashboard,
  },
  {
    id: 'system_monitor',
    label: '系统监控',
    description: '实时查看主机资源、CPU、内存、磁盘与网络趋势',
    group: '核心功能',
    icon: Monitor,
  },
  {
    id: 'task',
    label: '任务管理',
    description: '任务下发、全局查看、同名任务查看、批量停止/删除/导出',
    group: '核心功能',
    icon: Activity,
    listPath: '/task/',
    rowIdKey: '_id',
    defaultOrder: '-_id',
    quickFilterKey: 'name',
    showIndex: false,
    columns: ['name', 'target', 'statistic_summary', 'progress', 'options_summary', 'status', 'start_time', 'end_time', '_id'],
    columnLabels: {
      name: '任务名',
      target: '目标',
      statistic_summary: '统计',
      options_summary: '配置项',
      progress: '扫描进度',
      status: '状态',
      start_time: '开始时间',
      end_time: '结束时间',
      _id: 'Task_Id',
    },
    searchFields: [
      {
        key: 'name',
        label: '任务名',
        placeholder: '请输入或选择任务名（用于搜索/同名查看/批量操作）',
        dynamicOptionsKey: 'task_name',
      },
      { key: 'target', label: '目标', placeholder: '请输入目标进行搜索' },
      { key: '_id', label: 'Task_Id', placeholder: '请输入Task_Id进行搜索' },
      {
        key: 'status',
        label: '状态',
        placeholder: '请选择状态',
        inputType: 'select',
        options: [
          { label: '全部', value: '' },
          { label: '等待中', value: 'waiting' },
          { label: '运行中', value: 'running' },
          { label: '已完成', value: 'done' },
          { label: '已停止', value: 'stop' },
          { label: '异常', value: 'error' },
        ],
      },
      {
        key: 'type',
        label: '任务类型',
        placeholder: '请选择任务类型',
        inputType: 'select',
        options: [
          { label: '全部', value: '' },
          { label: '域名任务', value: 'domain' },
          { label: 'IP任务', value: 'ip' },
          { label: '风险巡航任务', value: 'risk_cruising' },
          { label: '测绘任务', value: 'fofa' },
          { label: '添加站点任务', value: 'asset_site_add' },
        ],
      },
    ],
    exportPath: '/export/{task_id}',
    actions: [
      {
        id: 'create_task',
        label: '新建任务',
        method: 'POST',
        path: '/task/',
        payloadTemplate: {
          name: '新扫描任务',
          target: 'example.com',
          domain_brute: true,
          domain_brute_type: 'big',
          domain_dict: '',
          file_leak_dict: '',
          port_scan: true,
          port_scan_type: 'test',
          port_custom: '80,443',
          service_detection: true,
          service_brute: false,
          os_detection: true,
          site_identify: true,
          site_capture: false,
          file_leak: true,
          search_engines: true,
          site_spider: true,
          arl_search: true,
          alt_dns: true,
          ssl_cert: true,
          dns_query_plugin: true,
          skip_scan_cdn_ip: true,
          nuclei_scan: true,
          afrog_scan: true,
          findvhost: true,
          web_info_hunter: true,
          smart_skip_waf: true,
          ai_denoise: true,
          dingding_notify: false,
        },
      },
      {
        id: 'fofa_submit',
        label: '测绘任务下发',
        method: 'POST',
        path: '/task_fofa/submit',
        payloadTemplate: {
          provider: 'fofa',
          query: 'domain="example.com"',
          name: '测绘任务',
          policy_id: '',
        },
      },
      {
        id: 'task_stop_batch',
        label: '批量停止',
        method: 'POST',
        path: '/task/batch_stop/',
        selectedField: 'task_id',
        selectionMode: 'multiple',
        payloadTemplate: {
          task_id: [],
        },
      },
      {
        id: 'task_restart_batch',
        label: '重启所选',
        method: 'POST',
        path: '/task/restart/',
        selectedField: 'task_id',
        selectionMode: 'multiple',
        payloadTemplate: {
          task_id: [],
        },
      },
      {
        id: 'task_delete_batch',
        label: '批量删除',
        method: 'POST',
        path: '/task/delete/',
        selectedField: 'task_id',
        selectionMode: 'multiple',
        payloadTemplate: {
          task_id: [],
          del_task_data: true,
        },
      },
      {
        id: 'task_policy_submit',
        label: '策略下发',
        method: 'POST',
        path: '/task/policy/',
        payloadTemplate: {
          name: '策略任务',
          task_tag: 'task',
          target: 'example.com',
          policy_id: '',
          result_set_id: '',
        },
      },
      {
        id: 'task_sync',
        label: '同步资产组',
        method: 'POST',
        path: '/task/sync/',
        payloadTemplate: {
          task_id: '',
          scope_id: '',
        },
      },
      {
        id: 'task_sync_scope_lookup',
        label: '匹配资产组',
        method: 'GET',
        path: '/task/sync_scope/',
        payloadTemplate: {
          target: 'www.example.com',
        },
        sendPayloadAsQuery: true,
      },
      {
        id: 'task_batch_export_site',
        label: '站点批量导出',
        method: 'POST',
        path: '/batch_export/site/',
        selectedField: 'task_id',
        selectionMode: 'multiple',
        payloadTemplate: {
          task_id: [],
        },
        download: true,
      },
      {
        id: 'task_batch_export_domain',
        label: '域名批量导出',
        method: 'POST',
        path: '/batch_export/domain/',
        selectedField: 'task_id',
        selectionMode: 'multiple',
        payloadTemplate: {
          task_id: [],
        },
        download: true,
      },
      {
        id: 'task_batch_export_ip',
        label: 'IP批量导出',
        method: 'POST',
        path: '/batch_export/ip/',
        selectedField: 'task_id',
        selectionMode: 'multiple',
        payloadTemplate: {
          task_id: [],
        },
        download: true,
      },
      {
        id: 'task_batch_export_url',
        label: 'URL批量导出',
        method: 'POST',
        path: '/batch_export/url/',
        selectedField: 'task_id',
        selectionMode: 'multiple',
        payloadTemplate: {
          task_id: [],
        },
        download: true,
      },
      {
        id: 'task_batch_export_fileleak',
        label: '目录扫描批量导出',
        method: 'POST',
        path: '/batch_export/fileleak/',
        selectedField: 'task_id',
        selectionMode: 'multiple',
        payloadTemplate: {
          task_id: [],
        },
        download: true,
      },
      {
        id: 'task_batch_export_port',
        label: 'IP端口批量导出',
        method: 'POST',
        path: '/batch_export/ip_port/',
        selectedField: 'task_id',
        selectionMode: 'multiple',
        payloadTemplate: {
          task_id: [],
        },
        download: true,
      },
      {
        id: 'task_batch_export_cip',
        label: 'C段批量导出',
        method: 'POST',
        path: '/batch_export/cip/',
        selectedField: 'task_id',
        selectionMode: 'multiple',
        payloadTemplate: {
          task_id: [],
        },
        download: true,
      },
      {
        id: 'task_batch_excel_report',
        label: '报告导出',
        method: 'POST',
        path: '/export/batch',
        selectedField: 'task_ids',
        selectionMode: 'multiple',
        payloadTemplate: {
          task_ids: [],
        },
        download: true,
      },
      {
        id: 'task_download_single_report',
        label: '下载单任务报告',
        method: 'GET',
        path: '/export/{task_id}',
        selectedField: 'task_id',
        selectionMode: 'single',
        payloadTemplate: {
          task_id: '',
        },
        download: true,
      },
    ],
  },
  {
    id: 'task_schedule',
    label: '计划任务',
    description: 'future_scan / recurrent_scan 计划调度',
    group: '核心功能',
    icon: Settings,
    listPath: '/task_schedule/',
    rowIdKey: '_id',
    defaultOrder: '-_id',
    quickFilterKey: 'name',
    showIndex: true,
    columns: ['name', 'target', 'schedule_type', 'status', 'policy_name', 'time_config', 'last_run_date', 'next_run_date', 'run_number'],
    columnLabels: {
      name: '任务名',
      target: '目标',
      schedule_type: '类型',
      status: '状态',
      policy_name: '策略',
      time_config: '时间配置',
      last_run_date: '上次运行时间',
      next_run_date: '下次运行时间',
      run_number: '运行次数',
    },
    searchFields: [
      { key: 'name', label: '任务名称', placeholder: '请输入任务名称进行搜索' },
      { key: 'target', label: '目标', placeholder: '请输入目标进行搜索' },
      {
        key: 'policy_name',
        label: '策略名称',
        placeholder: '请选择策略名称',
        inputType: 'select',
        dynamicOptionsKey: 'policy_name',
      },
      {
        key: 'schedule_type',
        label: '计划类型',
        placeholder: '请选择计划类型',
        inputType: 'select',
        options: [
          { label: '全部', value: '' },
          { label: '定时下发', value: 'future_scan' },
          { label: '周期下发', value: 'recurrent_scan' },
        ],
      },
      {
        key: 'schedule_status',
        label: '状态',
        placeholder: '请选择状态',
        inputType: 'select',
        options: [
          { label: '全部', value: '' },
          { label: '待调度', value: 'scheduled' },
          { label: '已停止', value: 'stop' },
          { label: '已完成', value: 'done' },
          { label: '异常', value: 'error' },
        ],
      },
    ],
    actions: [
      {
        id: 'task_schedule_add',
        label: '添加计划任务',
        method: 'POST',
        path: '/task_schedule/',
        payloadTemplate: {
          name: '计划任务',
          target: 'example.com',
          schedule_type: 'future_scan',
          policy_id: '',
          cron: '0 2 * * *',
          start_date: '',
          task_tag: 'task',
          notify_enable: true,
          notify_kb_enable: false,
          notify_channel: 'dingding',
          notify_on: 'finished',
        },
      },
      {
        id: 'task_schedule_stop',
        label: '批量停止',
        method: 'POST',
        path: '/task_schedule/stop/',
        selectedField: '_id',
        selectionMode: 'multiple',
        payloadTemplate: { _id: [] },
      },
      {
        id: 'task_schedule_recover',
        label: '批量恢复',
        method: 'POST',
        path: '/task_schedule/recover/',
        selectedField: '_id',
        selectionMode: 'multiple',
        payloadTemplate: { _id: [] },
      },
      {
        id: 'task_schedule_delete',
        label: '批量删除',
        method: 'POST',
        path: '/task_schedule/delete/',
        selectedField: '_id',
        selectionMode: 'multiple',
        payloadTemplate: { _id: [] },
      },
    ],
  },
  {
    id: 'scheduler',
    label: '资产监控',
    description: '资产监控任务查询与批量启停管理',
    group: '核心功能',
    icon: Monitor,
    listPath: '/scheduler/',
    rowIdKey: '_id',
    defaultOrder: '-_id',
    quickFilterKey: 'name',
    showIndex: true,
    columns: ['name', 'domain', 'scope_id', 'interval', 'last_run_date', 'next_run_date', 'run_number'],
    sortableColumns: ['domain', 'run_number'],
    columnLabels: {
      name: '名称',
      domain: '域名',
      scope_id: '资产组范围ID',
      interval: '运行间隔',
      last_run_date: '上一次运行日期',
      next_run_date: '下一次运行日期',
      run_number: '运行次数',
    },
    searchFields: [
      { key: 'name', label: '名称', placeholder: '请输入名称进行搜索' },
      { key: 'domain', label: '域名', placeholder: '请输入域名进行搜索' },
      { key: 'scope_id', label: '资产范围ID', placeholder: '请输入资产范围ID进行搜索' },
    ],
    actions: [
      {
        id: 'scheduler_delete',
        label: '批量删除',
        method: 'POST',
        path: '/scheduler/delete/',
        selectedField: 'job_id',
        selectionMode: 'multiple',
        payloadTemplate: { job_id: [] },
      },
      {
        id: 'scheduler_stop',
        label: '批量停止',
        method: 'POST',
        path: '/scheduler/stop/batch',
        selectedField: 'job_id',
        selectionMode: 'multiple',
        payloadTemplate: { job_id: [] },
      },
      {
        id: 'scheduler_recover',
        label: '批量恢复',
        method: 'POST',
        path: '/scheduler/recover/batch',
        selectedField: 'job_id',
        selectionMode: 'multiple',
        payloadTemplate: { job_id: [] },
      },
    ],
  },
  {
    id: 'policy',
    label: '策略配置',
    description: '策略增删改查及任务选项模板',
    group: '核心功能',
    icon: Wrench,
    listPath: '/policy/',
    rowIdKey: '_id',
    defaultOrder: '-_id',
    quickFilterKey: 'name',
    showIndex: true,
    columns: ['name', 'desc', 'update_date'],
    columnLabels: {
      name: '名称',
      desc: '描述',
      update_date: '更新时间',
    },
    searchFields: [{ key: 'name', label: '策略名称', placeholder: '请输入策略名称进行搜索' }],
    actions: [
      {
        id: 'policy_add',
        label: '新增策略',
        method: 'POST',
        path: '/policy/add/',
        payloadTemplate: {
          name: '默认策略',
          desc: '自动化创建',
          policy: {
            domain_config: {
              domain_brute: true,
              domain_brute_type: 'big',
              alt_dns: false,
              arl_search: false,
              dns_query_plugin: false,
            },
            ip_config: {
              port_scan: true,
              port_scan_type: 'test',
              service_detection: false,
              os_detection: false,
              ssl_cert: false,
              skip_scan_cdn_ip: true,
              port_custom: '80,443',
              host_timeout_type: 'default',
              host_timeout: 900,
              port_parallelism: 32,
              port_min_rate: 60,
            },
            site_config: {
              site_identify: false,
              site_capture: false,
              search_engines: false,
              site_spider: false,
              nuclei_scan: false,
              afrog_scan: false,
              web_info_hunter: false,
              smart_skip_waf: false,
              ai_denoise: true,
            },
            domain_dict: '',
            file_leak_dict: '',
            file_leak: false,
            npoc_service_detection: false,
            poc_config: [],
            brute_config: [],
            scope_config: {
              scope_id: '',
            },
          },
        },
      },
      {
        id: 'policy_edit',
        label: '更新策略',
        method: 'POST',
        path: '/policy/edit/',
        payloadTemplate: {
          policy_id: '',
          policy_data: {
            name: '更新后的策略名',
          },
        },
      },
      {
        id: 'policy_delete',
        label: '删除所选',
        method: 'POST',
        path: '/policy/delete/',
        selectedField: 'policy_id',
        selectionMode: 'multiple',
        payloadTemplate: { policy_id: [] },
      },
    ],
  },
  {
    id: 'asset_scope',
    label: '资产分组',
    description: '资产分组查询与维护',
    group: '核心功能',
    icon: Shield,
    listPath: '/asset_scope/',
    rowIdKey: '_id',
    defaultOrder: '-_id',
    quickFilterKey: 'name',
    exportPath: '/asset_scope/export/',
    columns: ['name', 'scope', '_id'],
    sortableColumns: ['name'],
    columnLabels: {
      name: '资产组名称',
      scope: '资产范围',
      _id: '资产范围ID',
    },
    searchFields: [
      { key: 'name', label: '资产组名称', placeholder: '请输入资产组名称进行搜索' },
      { key: 'scope', label: '资产范围', placeholder: '请输入资产范围进行搜索' },
      { key: '_id', label: '资产范围ID', placeholder: '请输入资产范围ID进行搜索' },
    ],
    actions: [
      {
        id: 'asset_scope_add',
        label: '新建资产分组',
        method: 'POST',
        path: '/asset_scope/',
        payloadTemplate: {
          name: '新资产组',
          scope: 'example.com',
          scope_type: 'domain',
        },
      },
      {
        id: 'asset_scope_delete',
        label: '批量删除',
        method: 'POST',
        path: '/asset_scope/delete/',
        selectedField: 'scope_id',
        selectionMode: 'multiple',
        payloadTemplate: { scope_id: [] },
      },
      {
        id: 'asset_scope_add_scope',
        label: '添加资产分组范围',
        method: 'POST',
        path: '/asset_scope/add/',
        payloadTemplate: {
          scope_id: '',
          scope: 'example.com',
        },
      },
      {
        id: 'asset_scope_update',
        label: '编辑资产',
        method: 'POST',
        path: '/asset_scope/update/',
        payloadTemplate: {
          scope_id: '',
          name: '',
          scope: 'example.com',
          black_scope: '',
        },
      },
      {
        id: 'asset_scope_add_scheduler',
        label: '添加监控任务',
        method: 'POST',
        path: '/scheduler/add/',
        payloadTemplate: {
          scope_id: '',
          domain: 'example.com',
          interval: 86400,
          name: '资产监控任务',
          policy_id: '',
        },
      },
      {
        id: 'asset_scope_add_site_monitor',
        label: '添加站点监控任务',
        method: 'POST',
        path: '/scheduler/add/site_monitor/',
        payloadTemplate: {
          scope_id: '',
          interval: 86400,
          name: '站点监控任务',
        },
      },
      {
        id: 'asset_scope_add_wih_monitor',
        label: '添加WIH监控任务',
        method: 'POST',
        path: '/scheduler/add/wih_monitor/',
        payloadTemplate: {
          scope_id: '',
          interval: 86400,
          name: 'WIH监控任务',
        },
      },
    ],
  },
  {
    id: 'asset_domain',
    label: '资产域名',
    description: '资产组内域名资产',
    group: '资产数据',
    icon: Globe,
    listPath: '/asset_domain/',
    rowIdKey: '_id',
    quickFilterKey: 'domain',
    showIndex: true,
    columns: ['domain', 'type', 'record', 'ips', 'source'],
    columnLabels: {
      domain: '域名',
      type: '解析类型',
      record: '记录值',
      ips: '关联IP',
      source: '来源',
    },
    searchFields: [
      { key: 'domain', label: '域名', placeholder: '请输入域名进行搜索' },
      { key: 'record', label: '记录值', placeholder: '请输入记录值进行搜索' },
      { key: 'type', label: '类型', placeholder: '请输入类型进行搜索' },
      { key: 'ips', label: 'IP', placeholder: '请输入IP进行搜索' },
      { key: 'source', label: '来源', placeholder: '请输入来源进行搜索' },
    ],
    exportPath: '/asset_domain/export/',
    actions: [
      {
        id: 'asset_domain_delete',
        label: '删除所选',
        method: 'POST',
        path: '/asset_domain/delete/',
        selectedField: '_id',
        selectionMode: 'multiple',
        payloadTemplate: { _id: [] },
      },
    ],
  },
  {
    id: 'asset_site',
    label: '资产站点',
    description: '资产组内站点资产',
    group: '资产数据',
    icon: Link,
    listPath: '/asset_site/',
    rowIdKey: '_id',
    quickFilterKey: 'site',
    showIndex: true,
    columns: ['site', 'title', 'headers', 'finger'],
    columnLabels: {
      site: '站点',
      title: '标题',
      headers: 'headers',
      finger: 'finger',
    },
    searchFields: [
      { key: 'site', label: '站点', placeholder: '请输入站点进行搜索' },
      { key: 'hostname', label: '主机名', placeholder: '请输入主机名进行搜索' },
      { key: 'title', label: '标题', placeholder: '请输入标题进行搜索' },
      { key: 'http_server', label: 'Web Server', placeholder: '请输入Web Server进行搜索' },
      { key: 'status', label: '状态码', placeholder: '请输入状态码进行搜索', inputType: 'number' },
      { key: 'headers', label: '标头', placeholder: '请输入标头进行搜索' },
      { key: 'finger.name', label: '指 纹', placeholder: '请输入指 纹进行搜索' },
      { key: 'favicon.hash', label: 'favicon hash', placeholder: '请输入favicon hash进行搜索', inputType: 'number' },
      { key: 'tag', label: '标签', placeholder: '请输入标签进行搜索' },
      {
        key: 'ai_analysis',
        label: 'AI分析',
        placeholder: '请选择AI分析结果',
        inputType: 'select',
        options: AI_ANALYSIS_SEARCH_OPTIONS,
      },
    ],
    exportPath: '/asset_site/export/',
    actions: [
      {
        id: 'asset_site_delete',
        label: '删除所选',
        method: 'POST',
        path: '/asset_site/delete/',
        selectedField: '_id',
        selectionMode: 'multiple',
        payloadTemplate: { _id: [] },
      },
      {
        id: 'asset_site_save_result_set',
        label: '保存结果集',
        method: 'GET',
        path: '/asset_site/save_result_set/',
        sendPayloadAsQuery: true,
        payloadTemplate: {
          scope_id: '',
          page: 1,
          size: 50,
        },
      },
    ],
  },
  {
    id: 'asset_ip',
    label: '资产IP',
    description: '资产组内IP资产',
    group: '资产数据',
    icon: Network,
    listPath: '/asset_ip/',
    rowIdKey: '_id',
    quickFilterKey: 'ip',
    showIndex: true,
    columns: ['ip', 'os_info.name', 'port_info.port_id', 'domain', 'cdn_name'],
    columnLabels: {
      ip: 'IP',
      'os_info.name': '操作系统',
      'port_info.port_id': '开放端口',
      domain: '关联域名',
      cdn_name: 'CDN',
    },
    searchFields: [
      { key: 'ip', label: 'IP', placeholder: '请输入IP进行搜索' },
      { key: 'port_info.port_id', label: '端口', placeholder: '请输入端口进行搜索', inputType: 'number' },
      { key: 'os_info.name', label: '操作系统', placeholder: '请输入操作系统进行搜索' },
      { key: 'domain', label: '域名', placeholder: '请输入域名进行搜索' },
      { key: 'cdn_name', label: 'CDN', placeholder: '请输入CDN进行搜索' },
    ],
    exportPath: '/asset_ip/export/',
    actions: [
      {
        id: 'asset_ip_delete',
        label: '删除所选',
        method: 'POST',
        path: '/asset_ip/delete/',
        selectedField: '_id',
        selectionMode: 'multiple',
        payloadTemplate: { _id: [] },
      },
    ],
  },
  {
    id: 'asset_wih',
    label: '资产WIH',
    description: '资产组内 JS 信息猎取数据',
    group: '资产数据',
    icon: FileCode,
    listPath: '/asset_wih/',
    rowIdKey: '_id',
    quickFilterKey: 'content',
    exportPath: '/asset_wih/export/',
  },
  {
    id: 'site',
    label: '站点',
    description: '任务扫描站点数据',
    group: '资产数据',
    icon: Globe,
    listPath: '/site/',
    rowIdKey: '_id',
    showIndex: true,
    quickFilterKey: 'site',
    columns: ['site', 'title', 'headers', 'finger', 'screenshot', 'ai_analysis'],
    columnLabels: {
      site: '站点',
      title: '标题',
      headers: 'headers',
      finger: 'finger',
      screenshot: '截图',
      ai_analysis: 'AI分析',
    },
    searchFields: [
      { key: 'site', label: '站点', placeholder: '请输入站点进行搜索' },
      { key: 'hostname', label: '主机名', placeholder: '请输入主机名进行搜索' },
      { key: 'title', label: '标题', placeholder: '请输入标题进行搜索' },
      { key: 'http_server', label: 'Web Server', placeholder: '请输入Web Server进行搜索' },
      { key: 'status', label: '状态码', placeholder: '请输入状态码进行搜索', inputType: 'number' },
      { key: 'headers', label: '标头', placeholder: '请输入标头进行搜索' },
      { key: 'finger.name', label: '指 纹', placeholder: '请输入指 纹进行搜索' },
      { key: 'favicon.hash', label: 'favicon hash', placeholder: '请输入favicon hash进行搜索', inputType: 'number' },
      { key: 'tag', label: '标签', placeholder: '请输入标签进行搜索' },
      {
        key: 'ai_analysis',
        label: 'AI分析',
        placeholder: '请选择AI分析结果',
        inputType: 'select',
        options: AI_ANALYSIS_SEARCH_OPTIONS,
      },
    ],
    exportPath: '/site/export/',
    actions: [
      {
        id: 'site_delete',
        label: '删除所选',
        method: 'POST',
        path: '/site/delete/',
        selectedField: '_id',
        selectionMode: 'multiple',
        payloadTemplate: {
          _id: [],
        },
      },
      {
        id: 'site_save_result_set',
        label: '保存结果集',
        method: 'GET',
        path: '/site/save_result_set/',
        sendPayloadAsQuery: true,
        payloadTemplate: {
          page: 1,
          size: 50,
        },
      },
    ],
  },
  {
    id: 'domain',
    label: '子域名',
    description: '任务扫描域名数据',
    group: '资产数据',
    icon: Globe,
    listPath: '/domain/',
    rowIdKey: '_id',
    showIndex: true,
    quickFilterKey: 'domain',
    columns: ['domain', 'type', 'record', 'ips', 'source'],
    columnLabels: {
      domain: '域名',
      type: '解析类型',
      record: '记录值',
      ips: '关联IP',
      source: '来源',
    },
    searchFields: [
      { key: 'domain', label: '域名', placeholder: '请输入域名进行搜索' },
      { key: 'record', label: '记录值', placeholder: '请输入记录值进行搜索' },
      { key: 'type', label: '类型', placeholder: '请输入类型进行搜索' },
      { key: 'ips', label: 'IP', placeholder: '请输入IP进行搜索' },
      { key: 'source', label: '来源', placeholder: '请输入来源进行搜索' },
    ],
    exportPath: '/domain/export/',
    actions: [
      {
        id: 'domain_delete',
        label: '删除所选',
        method: 'POST',
        path: '/domain/delete/',
        selectedField: '_id',
        selectionMode: 'multiple',
        payloadTemplate: { _id: [] },
      },
    ],
  },
  {
    id: 'ip',
    label: 'IP',
    description: '任务扫描IP和端口数据',
    group: '资产数据',
    icon: Network,
    listPath: '/ip/',
    rowIdKey: '_id',
    showIndex: true,
    quickFilterKey: 'ip',
    columns: ['ip', 'os_info.name', 'port_info.port_id', 'domain', 'cdn_name', 'geo_summary', 'asn_summary'],
    columnLabels: {
      ip: 'IP',
      'os_info.name': '操作系统',
      'port_info.port_id': '开放端口',
      domain: '关联域名',
      cdn_name: 'CDN',
      geo_summary: 'Geo',
      asn_summary: 'AS',
    },
    searchFields: [
      { key: 'ip', label: 'IP', placeholder: '请输入IP进行搜索' },
      { key: 'port_info.port_id', label: '端口', placeholder: '请输入端口进行搜索', inputType: 'number' },
      { key: 'os_info.name', label: '操作系统', placeholder: '请输入操作系统进行搜索' },
      { key: 'domain', label: '域名', placeholder: '请输入域名进行搜索' },
      { key: 'cdn_name', label: 'CDN', placeholder: '请输入CDN进行搜索' },
      {
        key: 'ip_type',
        label: 'IP类别',
        placeholder: '请选择IP类别',
        inputType: 'select',
        options: [
          { label: '全部', value: '' },
          { label: '内网', value: 'PRIVATE' },
          { label: '公网', value: 'PUBLIC' },
        ],
      },
    ],
    exportPath: '/ip/export/',
    actions: [
      {
        id: 'ip_export_ip',
        label: '导出纯IP',
        method: 'GET',
        path: '/ip/export_ip/',
        download: true,
      },
      {
        id: 'ip_export_domain',
        label: '导出域名',
        method: 'GET',
        path: '/ip/export_domain/',
        download: true,
      },
      {
        id: 'ip_delete',
        label: '删除所选',
        method: 'POST',
        path: '/ip/delete/',
        selectedField: '_id',
        selectionMode: 'multiple',
        payloadTemplate: { _id: [] },
      },
    ],
  },
  {
    id: 'url',
    label: 'URL信息',
    description: '任务URL结果',
    group: '资产数据',
    icon: Link,
    listPath: '/url/',
    rowIdKey: '_id',
    showIndex: true,
    quickFilterKey: 'url',
    columns: ['url', 'title', 'status_code', 'content_length', 'source', 'ai_analysis'],
    sortableColumns: ['content_length'],
    columnLabels: {
      url: 'URL',
      title: '标题',
      status_code: '状态码',
      content_length: 'body 长度',
      source: '来源',
      ai_analysis: 'AI分析',
    },
    searchFields: [
      { key: 'url', label: 'URL', placeholder: '请输入URL进行搜索' },
      { key: 'title', label: '标题', placeholder: '请输入标题进行搜索' },
      { key: 'status_code', label: '状态码', placeholder: '请输入状态码进行搜索', inputType: 'number' },
      { key: 'content_length', label: 'body 长度', placeholder: '请输入body 长度进行搜索', inputType: 'number' },
      { key: 'source', label: '来源', placeholder: '请输入来源进行搜索' },
      {
        key: 'ai_analysis',
        label: 'AI分析',
        placeholder: '请选择AI分析结果',
        inputType: 'select',
        options: AI_ANALYSIS_SEARCH_OPTIONS,
      },
    ],
    exportPath: '/url/export/',
  },
  {
    id: 'cert',
    label: 'SSL证书',
    description: 'TLS证书资产',
    group: '资产数据',
    icon: Shield,
    listPath: '/cert/',
    rowIdKey: '_id',
    showIndex: true,
    quickFilterKey: 'ip',
    columns: ['host', 'cert_summary', 'ai_analysis'],
    columnLabels: {
      host: 'HOST',
      cert_summary: 'CERT',
      ai_analysis: 'AI分析',
    },
    searchFields: [
      { key: 'ip', label: 'IP字段', placeholder: '请输入IP字段进行搜索' },
      { key: 'cert.issuer_dn', label: '签发者名称', placeholder: '请输入签发者名称进行搜索' },
      { key: 'cert.subject_dn', label: '主题名称', placeholder: '请输入主题名称进行搜索' },
      { key: 'cert.fingerprint.sha1', label: 'SHA-1', placeholder: '请输入SHA-1进行搜索' },
      {
        key: 'cert.extensions.subjectAltName',
        label: '使用者备用名称',
        placeholder: '请输入使用者备用名称进行搜索',
      },
      {
        key: 'ai_analysis',
        label: 'AI分析',
        placeholder: '请选择AI分析结果',
        inputType: 'select',
        options: AI_ANALYSIS_SEARCH_OPTIONS,
      },
    ],
    actions: [
      {
        id: 'cert_delete',
        label: '删除所选',
        method: 'POST',
        path: '/cert/delete/',
        selectedField: '_id',
        selectionMode: 'multiple',
        payloadTemplate: { _id: [] },
      },
    ],
  },
  {
    id: 'service',
    label: '服务',
    description: '端口服务识别结果',
    group: '资产数据',
    icon: Server,
    listPath: '/service/',
    rowIdKey: '_id',
    showIndex: true,
    quickFilterKey: 'service_name',
    columns: ['service_name', 'ip_port', 'service_info.product'],
    columnLabels: {
      service_name: '服务',
      ip_port: 'IP端口',
      'service_info.product': 'Product',
    },
    searchFields: [
      { key: 'service_name', label: '服务', placeholder: '请输入服务进行搜索' },
      { key: 'service_info.ip', label: 'IP', placeholder: '请输入IP进行搜索' },
      { key: 'service_info.port_id', label: '端口', placeholder: '请输入端口进行搜索', inputType: 'number' },
      { key: 'service_info.product', label: '产品', placeholder: '请输入产品进行搜索' },
    ],
  },
  {
    id: 'npoc_service',
    label: 'C段',
    description: '协议探测与目标结果',
    group: '资产数据',
    icon: Terminal,
    listPath: '/npoc_service/',
    rowIdKey: '_id',
    showIndex: true,
    quickFilterKey: 'target',
    columns: ['scheme', 'host', 'port', 'target'],
    columnLabels: {
      scheme: '协议',
      host: '主机',
      port: '端口',
      target: '目标',
    },
    searchFields: [
      { key: 'scheme', label: '协议', placeholder: '请输入协议进行搜索' },
      { key: 'host', label: '主机', placeholder: '请输入主机进行搜索' },
      { key: 'port', label: '端口', placeholder: '请输入端口进行搜索' },
      { key: 'target', label: '目标', placeholder: '请输入目标进行搜索' },
    ],
  },
  {
    id: 'cip',
    label: 'C段',
    description: 'C段分布统计',
    group: '资产数据',
    icon: Database,
    listPath: '/cip/',
    rowIdKey: '_id',
    showIndex: true,
    quickFilterKey: 'cidr_ip',
    defaultOrder: '-ip_count',
    columns: ['cidr_ip', 'ip_count', 'domain_count'],
    sortableColumns: ['cidr_ip', 'ip_count', 'domain_count'],
    columnLabels: {
      cidr_ip: 'C段',
      ip_count: 'IP数',
      domain_count: '域名数',
    },
    searchFields: [
      { key: 'cidr_ip', label: 'C段', placeholder: '请输入C段进行搜索' },
    ],
    exportPath: '/cip/export/',
  },
  {
    id: 'stat_finger',
    label: '指纹统计',
    description: '识别指纹统计',
    group: '资产数据',
    icon: Activity,
    hidden: true,
    listPath: '/stat_finger/',
    rowIdKey: '_id',
    showIndex: true,
    quickFilterKey: 'name',
    defaultOrder: '-cnt',
    columns: ['name', 'cnt'],
    sortableColumns: ['cnt'],
    columnLabels: {
      name: 'finger',
      cnt: '数量',
    },
    searchFields: [
      { key: 'name', label: 'finger', placeholder: '请输入finger进行搜索' },
    ],
  },
  {
    id: 'vuln',
    label: '风险',
    description: '风险结果查询和处置',
    group: '风险与规则',
    icon: AlertTriangle,
    listPath: '/vuln/',
    rowIdKey: '_id',
    showIndex: true,
    quickFilterKey: 'vul_name',
    columns: ['vul_name', 'plg_type', 'app_name', 'target', 'credential', 'save_date', 'ai_analysis', 'detail_action'],
    columnLabels: {
      vul_name: '风险名称',
      plg_type: '类别',
      app_name: '应用名',
      target: '目标',
      credential: '凭证',
      save_date: '发现时间',
      ai_analysis: 'AI分析',
      detail_action: '详情信息',
    },
    searchFields: [
      { key: 'vul_name', label: '风险名称', placeholder: '请输入风险名称进行搜索' },
      {
        key: 'plg_type',
        label: '类别',
        placeholder: '请选择类别',
        inputType: 'select',
        dynamicOptionsKey: 'vuln_category',
      },
      { key: 'app_name', label: '应用名', placeholder: '请输入应用名进行搜索' },
      { key: 'target', label: '目标', placeholder: '请输入目标进行搜索' },
      {
        key: 'ai_analysis',
        label: 'AI分析',
        placeholder: '请选择AI分析结果',
        inputType: 'select',
        options: AI_ANALYSIS_SEARCH_OPTIONS,
      },
    ],
    actions: [
      {
        id: 'vuln_delete',
        label: '删除所选',
        method: 'POST',
        path: '/vuln/delete/',
        selectedField: '_id',
        selectionMode: 'multiple',
        payloadTemplate: { _id: [] },
      },
    ],
  },
  {
    id: 'nuclei_result',
    label: 'PoC风险',
    description: 'Nuclei / afrog PoC 扫描结果',
    group: '风险与规则',
    icon: FlaskConical,
    listPath: '/nuclei_result/',
    rowIdKey: '_id',
    showIndex: true,
    quickFilterKey: 'vuln_name',
    // 风险URL 从列表移除（易与目标混淆且冗长），详情弹窗内完整展示
    columns: ['scanner_type', 'rule_id', 'target', 'vuln_name', 'vuln_severity', 'save_date', 'verify_data', 'ai_analysis', 'detail_action'],
    columnLabels: {
      scanner_type: '扫描器',
      rule_id: '规则ID',
      target: '目标',
      vuln_url: '风险URL',
      vuln_name: '风险名称',
      vuln_severity: '风险等级',
      save_date: '保存时间',
      verify_data: '验证信息',
      ai_analysis: 'AI分析',
      detail_action: '详情信息',
    },
    searchFields: [
      {
        key: 'scanner_type',
        label: '扫描器',
        placeholder: '请选择扫描器',
        inputType: 'select',
        options: [
          { label: '全部', value: '' },
          { label: 'Nuclei', value: 'nuclei' },
          { label: 'afrog', value: 'afrog' },
        ],
      },
      { key: 'rule_id', label: '规则ID', placeholder: '请输入模板ID或PoC ID进行搜索' },
      { key: 'target', label: '目标', placeholder: '请输入目标进行搜索' },
      { key: 'vuln_name', label: '风险名称', placeholder: '请输入风险名称进行搜索' },
      {
        key: 'ai_analysis',
        label: 'AI分析',
        placeholder: '请选择AI分析结果',
        inputType: 'select',
        options: AI_ANALYSIS_SEARCH_OPTIONS,
      },
    ],
    actions: [
      {
        id: 'nuclei_result_delete',
        label: '删除所选',
        method: 'POST',
        path: '/nuclei_result/delete/',
        selectedField: '_id',
        selectionMode: 'multiple',
        payloadTemplate: { _id: [] },
      },
    ],
  },
  {
    id: 'fileleak',
    label: '目录扫描',
    description: '目录扫描结果',
    group: '风险与规则',
    icon: ShieldAlert,
    listPath: '/fileleak/',
    rowIdKey: '_id',
    showIndex: true,
    quickFilterKey: 'url',
    columns: ['url', 'title', 'status_code', 'content_length', 'source', 'ai_analysis'],
    sortableColumns: ['content_length'],
    columnLabels: {
      url: 'URL',
      title: '标题',
      status_code: '状态码',
      content_length: 'body 长度',
      source: '来源',
      ai_analysis: 'AI分析',
    },
    searchFields: [
      { key: 'url', label: 'URL', placeholder: '请输入URL进行搜索' },
      { key: 'title', label: '标题', placeholder: '请输入标题进行搜索' },
      { key: 'status_code', label: '状态码', placeholder: '请输入状态码进行搜索', inputType: 'number' },
      { key: 'content_length', label: 'body 长度', placeholder: '请输入body 长度进行搜索', inputType: 'number' },
      {
        key: 'source',
        label: '来源',
        placeholder: '请选择来源',
        inputType: 'select',
        options: [
          { label: '全部', value: '' },
          { label: '字典爆破', value: 'dict_brute' },
        ],
      },
      {
        key: 'ai_analysis',
        label: 'AI分析',
        placeholder: '请选择AI分析结果',
        inputType: 'select',
        options: AI_ANALYSIS_SEARCH_OPTIONS,
      },
    ],
    actions: [
      {
        id: 'fileleak_delete',
        label: '删除所选',
        method: 'POST',
        path: '/fileleak/delete/',
        selectedField: '_id',
        selectionMode: 'multiple',
        payloadTemplate: { _id: [] },
      },
    ],
    exportPath: '/fileleak/export/',
  },
  {
    id: 'wih',
    label: 'WIH',
    description: '任务中提取的JS信息',
    group: '风险与规则',
    icon: FileCode,
    listPath: '/wih/',
    rowIdKey: '_id',
    showIndex: true,
    quickFilterKey: 'content',
    columns: ['record_type', 'content', 'source', 'site'],
    columnLabels: {
      record_type: '记录类型',
      content: '内容',
      source: '来源 JS',
      site: '来源站点',
    },
    searchFields: [
      { key: 'record_type', label: '记录类型', placeholder: '请输入记录类型进行搜索' },
      { key: 'content', label: '内容', placeholder: '请输入内容进行搜索' },
      { key: 'source', label: '来源 JS', placeholder: '请输入来源 JS进行搜索' },
      { key: 'site', label: '来源站点', placeholder: '请输入来源站点进行搜索' },
    ],
    exportPath: '/wih/export/',
  },
  {
    id: 'wih_endpoint',
    label: 'WIH接口提取',
    description: 'WIH 结构化接口提取结果',
    group: '风险与规则',
    icon: FileCode,
    listPath: '/wih_endpoint/',
    rowIdKey: '_id',
    showIndex: true,
    quickFilterKey: 'url',
    // 主列用接口自身的 url（请求报文目标）；page_url 仅保留在详情弹窗与搜索中
    columns: ['target', 'url', 'method', 'status_code', 'response_size', 'ai_analysis', 'detail_action'],
    sortableColumns: ['status_code', 'response_size'],
    columnLabels: {
      target: '目标',
      url: '接口URL',
      page_url: '页面URL',
      method: '方法',
      status_code: '状态码',
      response_size: '响应大小',
      ai_analysis: 'AI分析',
      detail_action: '详情信息',
    },
    searchFields: [
      { key: 'target', label: '目标', placeholder: '请输入目标进行搜索' },
      { key: 'page_url', label: '页面URL', placeholder: '请输入页面URL进行搜索' },
      { key: 'url', label: '接口URL', placeholder: '请输入接口URL进行搜索' },
      {
        key: 'method',
        label: '方法',
        placeholder: '请选择方法',
        inputType: 'select',
        options: [
          { label: '全部', value: '' },
          { label: 'GET', value: 'GET' },
          { label: 'POST', value: 'POST' },
        ],
      },
      { key: 'status_code', label: '状态码', placeholder: '请输入状态码进行搜索', inputType: 'number' },
      { key: 'response_size', label: '响应大小', placeholder: '请输入响应大小进行搜索', inputType: 'number' },
      {
        key: 'ai_analysis',
        label: 'AI分析',
        placeholder: '请选择价值等级',
        inputType: 'select',
        options: AI_WIH_ENDPOINT_ANALYSIS_SEARCH_OPTIONS,
      },
    ],
    actions: [
      {
        id: 'wih_endpoint_delete',
        label: '删除所选',
        method: 'POST',
        path: '/wih_endpoint/delete/',
        selectedField: '_id',
        selectionMode: 'multiple',
        payloadTemplate: { _id: [] },
      },
    ],
    exportPath: '/wih_endpoint/export/',
  },
  {
    id: 'waf_host',
    label: 'WAF识别',
    description: '任务中被 WAF 智能跳过的主机',
    group: '风险与规则',
    icon: ShieldAlert,
    listPath: '/waf_host/',
    rowIdKey: '_id',
    showIndex: true,
    quickFilterKey: 'domain',
    columns: ['ip', 'domain', 'port', 'waf_name', 'hit_rule'],
    columnLabels: {
      ip: 'IP',
      domain: '域名',
      port: '端口',
      waf_name: 'WAF厂家',
      hit_rule: '命中规则',
    },
    searchFields: [
      { key: 'ip', label: 'IP', placeholder: '请输入IP进行搜索' },
      { key: 'domain', label: '域名', placeholder: '请输入域名进行搜索' },
      { key: 'port', label: '端口', placeholder: '请输入端口进行搜索', inputType: 'number' },
      { key: 'waf_name', label: 'WAF厂家', placeholder: '请输入WAF厂家进行搜索' },
      { key: 'hit_rule', label: '命中规则', placeholder: '请输入命中规则或命中理由进行搜索' },
    ],
  },
  {
    id: 'poc',
    label: 'PoC管理',
    description: 'PoC / brute 插件管理',
    group: '风险与规则',
    icon: Shield,
    listPath: '/poc/',
    rowIdKey: '_id',
    quickFilterKey: 'plugin_name',
    showIndex: true,
    columns: ['plugin_name', 'plugin_type', 'category', 'app_name', 'vul_name', 'scheme', 'update_date'],
    columnLabels: {
      plugin_name: '插件名称',
      plugin_type: '类型',
      category: '分类',
      app_name: '应用',
      vul_name: '风险名称',
      scheme: '协议',
      update_date: '更新时间',
    },
    actions: [
      {
        id: 'poc_sync',
        label: '同步PoC',
        method: 'GET',
        path: '/poc/sync/',
      },
      {
        id: 'poc_clear',
        label: '清空PoC库',
        method: 'GET',
        path: '/poc/delete/',
      },
    ],
  },
  {
    id: 'fingerprint',
    label: '指纹规则',
    description: 'Web 指纹规则管理（支持 body/header/title/icon_hash/response/url）',
    group: '风险与规则',
    icon: FileCode,
    listPath: '/fingerprint/',
    rowIdKey: '_id',
    quickFilterKey: 'name',
    showIndex: true,
    columns: ['name', 'human_rule', 'update_date'],
    columnLabels: {
      name: '名称',
      human_rule: '规则',
      update_date: '更新时间',
    },
    actions: [
      {
        id: 'fingerprint_add',
        label: '新增指纹',
        method: 'POST',
        path: '/fingerprint/',
        payloadTemplate: {
          name: '自定义指纹',
          human_rule: 'header="Server: nginx" || url="/zentao/user"',
        },
      },
      {
        id: 'fingerprint_delete',
        label: '删除所选',
        method: 'POST',
        path: '/fingerprint/delete/',
        selectedField: '_id',
        selectionMode: 'multiple',
        payloadTemplate: { _id: [] },
      },
      {
        id: 'fingerprint_export',
        label: '导出规则',
        method: 'GET',
        path: '/fingerprint/export/',
        download: true,
      },
      {
        id: 'fingerprint_upload',
        label: '上传规则文件',
        method: 'POST',
        path: '/fingerprint/upload/',
        fileFieldName: 'file',
        fileAccept: '.yml,.yaml',
        allowPayloadEdit: false,
      },
    ],
  },
  {
    id: 'github_task',
    label: 'GitHub任务',
    description: 'GitHub 一次性检索任务',
    group: 'GitHub监控',
    icon: GitBranch,
    listPath: '/github_task/',
    rowIdKey: '_id',
    quickFilterKey: 'name',
    columns: ['name', 'keyword', 'result_count', 'status', 'start_time', 'end_time', '_id'],
    columnLabels: {
      name: '任务名',
      keyword: '关键字',
      result_count: '结果数目',
      status: '状态',
      start_time: '开始时间',
      end_time: '结束时间',
      _id: '任务id',
    },
    searchFields: [
      { key: 'name', label: '任务名称', placeholder: '请输入任务名称进行搜索' },
      { key: 'keyword', label: '关键字', placeholder: '请输入关键字进行搜索' },
      {
        key: 'status',
        label: '状态',
        placeholder: '请选择状态',
        inputType: 'select',
        options: [
          { label: '全部', value: '' },
          { label: '等待中', value: 'waiting' },
          { label: '运行中', value: 'running' },
          { label: '已完成', value: 'done' },
          { label: '已停止', value: 'stop' },
          { label: '异常', value: 'error' },
        ],
      },
    ],
    actions: [
      {
        id: 'github_task_add',
        label: '新增GitHub任务',
        method: 'POST',
        path: '/github_task/',
        payloadTemplate: {
          name: 'GitHub泄露检索',
          keyword: 'AKIA',
        },
      },
      {
        id: 'github_task_stop',
        label: '批量停止',
        method: 'POST',
        path: '/github_task/stop/',
        selectedField: '_id',
        selectionMode: 'multiple',
        payloadTemplate: { _id: [] },
      },
      {
        id: 'github_task_delete',
        label: '批量删除',
        method: 'POST',
        path: '/github_task/delete/',
        selectedField: '_id',
        selectionMode: 'multiple',
        payloadTemplate: { _id: [] },
      },
    ],
  },
  {
    id: 'github_result',
    label: 'GitHub结果',
    description: 'GitHub 泄露检索结果',
    group: 'GitHub监控',
    icon: Search,
    listPath: '/github_result/',
    rowIdKey: '_id',
    quickFilterKey: 'human_content',
    columns: ['repo_full_name', 'path', 'human_content', 'commit_date', 'keyword'],
    columnLabels: {
      repo_full_name: '仓库名',
      path: '路径',
      human_content: '内容',
      commit_date: '提交时间',
      keyword: '关键字',
    },
    searchFields: [
      { key: 'path', label: '路径名', placeholder: '请输入路径名进行搜索' },
      { key: 'repo_full_name', label: '仓库名', placeholder: '请输入仓库名进行搜索' },
      { key: 'human_content', label: '内容', placeholder: '请输入内容进行搜索' },
    ],
  },
  {
    id: 'github_scheduler',
    label: 'GitHub监控',
    description: 'GitHub 定时监控任务',
    group: 'GitHub监控',
    icon: RefreshCw,
    listPath: '/github_scheduler/',
    rowIdKey: '_id',
    quickFilterKey: 'name',
    columns: ['name', 'keyword', 'cron', 'status', 'run_number', 'last_run_date', 'next_run_date'],
    columnLabels: {
      name: '任务名',
      keyword: '关键字',
      cron: 'cron表达式',
      status: '状态',
      run_number: '运行次数',
      last_run_date: '上次运行时间',
      next_run_date: '下次运行时间',
    },
    searchFields: [
      { key: 'name', label: '任务名称', placeholder: '请输入任务名称进行搜索' },
      { key: 'keyword', label: '关键字', placeholder: '请输入关键字进行搜索' },
      {
        key: 'status',
        label: '状态',
        placeholder: '请选择状态',
        inputType: 'select',
        options: [
          { label: '全部', value: '' },
          { label: '运行中', value: 'running' },
          { label: '停止', value: 'stop' },
        ],
      },
    ],
    actions: [
      {
        id: 'github_scheduler_add',
        label: '添加任务',
        method: 'POST',
        path: '/github_scheduler/',
        payloadTemplate: {
          name: 'GitHub监控任务',
          keyword: 'AKIA',
          cron: '0 */6 * * *',
          dingding_notify: true,
          kb_notify_enable: false,
        },
      },
      {
        id: 'github_scheduler_update',
        label: '更新监控任务',
        method: 'POST',
        path: '/github_scheduler/update/',
        payloadTemplate: {
          _id: '',
          name: 'GitHub监控更新',
          keyword: 'sk_live_',
          cron: '0 */6 * * *',
          dingding_notify: true,
          kb_notify_enable: false,
        },
      },
      {
        id: 'github_scheduler_stop',
        label: '批量停止',
        method: 'POST',
        path: '/github_scheduler/stop/',
        selectedField: '_id',
        selectionMode: 'multiple',
        payloadTemplate: { _id: [] },
      },
      {
        id: 'github_scheduler_recover',
        label: '恢复所选',
        method: 'POST',
        path: '/github_scheduler/recover/',
        selectedField: '_id',
        selectionMode: 'multiple',
        payloadTemplate: { _id: [] },
      },
      {
        id: 'github_scheduler_delete',
        label: '批量删除',
        method: 'POST',
        path: '/github_scheduler/delete/',
        selectedField: '_id',
        selectionMode: 'multiple',
        payloadTemplate: { _id: [] },
      },
    ],
  },
  {
    id: 'github_monitor_result',
    label: 'GitHub监控结果',
    description: 'GitHub 定时任务结果',
    group: 'GitHub监控',
    icon: Search,
    listPath: '/github_monitor_result/',
    rowIdKey: '_id',
    quickFilterKey: 'human_content',
    columns: ['repo_full_name', 'path', 'human_content', 'commit_date', 'keyword'],
    columnLabels: {
      repo_full_name: '仓库名',
      path: '路径',
      human_content: '内容',
      commit_date: '提交时间',
      keyword: '关键字',
    },
    searchFields: [
      { key: 'path', label: '路径名', placeholder: '请输入路径名进行搜索' },
      { key: 'repo_full_name', label: '仓库名', placeholder: '请输入仓库名进行搜索' },
      { key: 'human_content', label: '内容', placeholder: '请输入内容进行搜索' },
    ],
  },
  {
    id: 'task_fofa',
    label: '测绘任务',
    description: 'FOFA / Hunter / Shodan / Zoomeye / Quake 语法测试与任务下发',
    group: '系统集成',
    icon: Search,
    actions: [
      {
        id: 'fofa_test',
        label: '测试测绘语法',
        method: 'POST',
        path: '/task_fofa/test',
        payloadTemplate: {
          provider: 'fofa',
          query: 'domain="example.com"',
        },
      },
      {
        id: 'fofa_submit_center',
        label: '提交测绘任务',
        method: 'POST',
        path: '/task_fofa/submit',
        payloadTemplate: {
          provider: 'fofa',
          query: 'domain="example.com"',
          name: '测绘批量任务',
          policy_id: '',
        },
      },
    ],
  },
  {
    id: 'dingtalk_api',
    label: '钉钉集成',
    description: '钉钉 OpenAPI 调试与知识库联动',
    group: '系统集成',
    icon: Settings,
    actions: [
      {
        id: 'dingtalk_config',
        label: '读取配置状态',
        method: 'GET',
        path: '/dingtalk_api/config/',
      },
      {
        id: 'dingtalk_test',
        label: '测试连通性',
        method: 'POST',
        path: '/dingtalk_api/test/',
        payloadTemplate: {
          force_refresh_token: false,
        },
      },
      {
        id: 'dingtalk_workspaces',
        label: '获取空间列表',
        method: 'POST',
        path: '/dingtalk_api/workspaces/',
        payloadTemplate: {
          operator_id: '',
        },
      },
      {
        id: 'dingtalk_nodes',
        label: '获取节点列表',
        method: 'POST',
        path: '/dingtalk_api/nodes/',
        payloadTemplate: {
          operator_id: '',
          parent_node_id: '',
        },
      },
      {
        id: 'dingtalk_create_workbook',
        label: '创建知识库表格',
        method: 'POST',
        path: '/dingtalk_api/create_workbook/',
        payloadTemplate: {
          title: 'ARL安全报告',
          operator_id: '',
          workspace_id: '',
          parent_node_id: '',
        },
      },
      {
        id: 'dingtalk_sheets',
        label: '获取工作表',
        method: 'POST',
        path: '/dingtalk_api/sheets/',
        payloadTemplate: {
          workbook_id: '',
          operator_id: '',
        },
      },
      {
        id: 'dingtalk_write_markdown',
        label: '写入Markdown',
        method: 'POST',
        path: '/dingtalk_api/write_markdown/',
        payloadTemplate: {
          workbook_id: '',
          sheet_name: 'Sheet1',
          markdown_content: '### ARL 通知测试',
          operator_id: '',
        },
      },
    ],
  },
  {
    id: 'api_console',
    label: 'API管理',
    description: '管理 FOFA / Hunter / Quake / Zoomeye 等三方 API 凭据',
    group: '系统集成',
    icon: Key,
  },
  {
    id: 'config_console',
    label: '配置管理',
    description: '管理扫描字典、并发参数、黑名单IP与域名解析器配置',
    group: '系统集成',
    icon: Settings,
  },
  {
    id: 'ai_console',
    label: 'AI管理',
    description: '管理AI模型、SOP模板、连通性测试与AI报告配置',
    group: '系统集成',
    icon: Sparkles,
  },
];

export const TASK_DETAIL_TABS: Array<{ id: string; label: string }> = [
  { id: 'site', label: '站点' },
  { id: 'domain', label: '子域名' },
  { id: 'ip', label: 'IP' },
  { id: 'cert', label: 'SSL证书' },
  { id: 'service', label: '服务' },
  { id: 'fileleak', label: '目录扫描' },
  { id: 'url', label: 'URL信息' },
  { id: 'vuln', label: '风险' },
  { id: 'nuclei_result', label: 'PoC风险' },
  { id: 'wih', label: 'WIH' },
  { id: 'wih_endpoint', label: 'WIH接口提取' },
  { id: 'waf_host', label: 'WAF识别' },
];

export const visibleModules = modules.filter((module) => !module.hidden);

export function getDefaultModulePageSize(moduleId: string, filters?: JsonValue): number {
  const isTaskDetailModule = TASK_DETAIL_TABS.some((tab) => tab.id === moduleId);
  if (!isTaskDetailModule) return 50;
  const taskId = String((filters || {}).task_id || '').trim();
  if (taskId) return 200;
  return 50;
}

export function isDeleteAction(action: ModuleAction): boolean {
  const id = String(action?.id || '').toLowerCase();
  const label = String(action?.label || '').toLowerCase();
  const path = String(action?.path || '').toLowerCase();
  return id.includes('delete') || label.includes('删除') || path.includes('/delete/');
}

export function getModuleById(id: string): ModuleConfig {
  return visibleModules.find((module) => module.id === id) || visibleModules[0];
}

export function resolveStoredModuleId(moduleId: string | null | undefined): string {
  const normalized = String(moduleId || '').trim();
  if (!normalized) return 'dashboard';
  return visibleModules.some((module) => module.id === normalized) ? normalized : 'dashboard';
}
